### ISSUE TITLE
[ enhancement ] setup github actions release flow

### ISSUE THREAD

**Issue by kilgore5** [kingandpartners/elastic-press#20]
once release is created:
- zip the package
- update packages.json file with latest release
- upload to s3 bucket for composer to access

**Comment by jGRUBBS** [comment]
I setup a `satis` repository [kingandpartners/kingandpartners-composer](https://github.com/kingandpartners/kingandpartners-composer) along with [Github Actions in this repository](https://github.com/kingandpartners/elastic-press/actions) to automate release management. See [kingandpartners/kingandpartners-composer](https://github.com/kingandpartners/kingandpartners-composer) for more information on how it works.
